### PR TITLE
Merge multiple branches

### PR DESCRIPTION
**Pull request by brandond**
LMTP support, init scripts for Ubuntu and Debian, syslog, and more.

### CODE REVIEW

**Comment by tomsommer** [comment]
This commit broke Centos 6 support, because IO::Socket::IP doesn't exist.

**Comment by brandond** [comment]
@tomsommer not available as RPM, or does it fail to install via CPAN as well? We could probably attempt to load IP and fall back to INET if not available, at the cost of IPv6 support.

**Comment by tomsommer** [comment]
Not available in RPM, neither in EPEL.

**Comment by brandond** [comment]
@tomsommer Just switched over to INET6 which seems to be more available, with the same functionality. Are you available to test?

**Comment by tomsommer** [comment]
Works like a charm. Thanks.

**Pull request closed without merging**
